# Manually triggered pipeline used to unlist packages on nuget.org

trigger:
- none

pr:
- none

variables:
- group: Xamarin-Secrets

jobs:
- job: push_nupkg
  displayName: Push Packages
  timeoutInMinutes: 90
  pool:
    name: AzurePipelines-EO
    demands:
    - ImageOverride -equals AzurePipelinesWindows2022compliant
  workspace:
    clean: all
  steps:
  - checkout: self

  - task: NuGetToolInstaller@1
    inputs:
      versionSpec: 5.x

  - task: DownloadPipelineArtifact@2
    displayName: download nuget-signed
    inputs:
      source: specific
      project: DevDiv
      pipeline: 14411
      runVersion: specific
      runId: 5862144
      artifactName: nuget-signed
      downloadPath: $(Build.StagingDirectory)\nuget-signed

  - task: DownloadPipelineArtifact@2
    displayName: download vs-msi-nugets
    inputs:
      source: specific
      project: DevDiv
      pipeline: 14411
      runVersion: specific
      runId: 5862144
      artifactName: vs-msi-nugets
      downloadPath: $(Build.StagingDirectory)\vs-msi-nugets

  - pwsh: Get-ChildItem -Name -Recurse -Path $(Build.StagingDirectory)
    displayName: list downloaded artifacts
