# Manually triggered pipeline used to unlist packages on nuget.org

trigger:
- none

pr:
- none

resources:
  repositories:
  - repository: sdk-insertions
    type: github
    name: xamarin/sdk-insertions
    ref: refs/heads/main
    endpoint: xamarin

variables:
- template: templates/common/vs-release-vars.yml@sdk-insertions
- group: Xamarin-Secrets

jobs:
- job: push_nupkg
  displayName: Push Packages
  timeoutInMinutes: 90
  pool:
    name: AzurePipelines-EO
    demands:
    - ImageOverride -equals AzurePipelinesWindows2022compliant
  workspace:
    clean: all
  steps:
  - checkout: self

  - task: NuGetToolInstaller@1
    inputs:
      versionSpec: 5.x

    - script: |
        echo ##vso[task.setvariable variable=COMMIT]8fcb97a072c10248ae01b52b60696b8e9e6c7a99
      displayName: set COMMIT

  - template: templates/common/download_artifacts.yml@sdk-insertions
    parameters:
      projectName: xamarin
      projectOrg: xamarin-macios
      artifactName: $(NupkgCommitStatusName)
      githubToken: $(github--pat--vs-mobiletools-engineering-service2)
      downloadFolder: $(Build.StagingDirectory)

  - pwsh: Get-ChildItem -Name -Recurse -Path $(Build.StagingDirectory)
    displayName: list downloaded artifacts

#  - task: NuGetCommand@2
#    displayName: push nupkgs
#    inputs:
#      command: push
#      packagesToPush: $(Build.StagingDirectory)\nuget-signed\*.nupkg
#      nuGetFeedType: external
#      publishFeedCredentials: Xamarin nuget.org - xamarinc

#  - task: NuGetCommand@2
#    displayName: push msi nupkgs
#    inputs:
#      command: push
#      packagesToPush: $(Build.StagingDirectory)\vs-msi-nugets\*.nupkg
#      nuGetFeedType: external
#      publishFeedCredentials: Xamarin nuget.org - xamarinc
